#!/usr/bin/env bash
# CodeDeploy AfterInstall: write .env from SSM Parameter Store, build the images.
set -euo pipefail
source "$(dirname "$0")/common.sh"

# Region of this instance, from the metadata service (IMDSv2).
token=$(curl -fsS -X PUT http://169.254.169.254/latest/api/token \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 300")
region=$(curl -fsS -H "X-aws-ec2-metadata-token: $token" \
  http://169.254.169.254/latest/meta-data/placement/region)

release=$(tr -d '[:space:]' < "$APP_DIR/RELEASE" 2>/dev/null || true)
release=${release:-${DEPLOYMENT_ID:-manual}}

log "loading parameters from SSM $SSM_PATH ($region)"
params=$(aws ssm get-parameters-by-path --region "$region" --path "$SSM_PATH" \
  --with-decryption --query 'Parameters[].[Name,Value]' --output text)

umask 077
{
  echo "# Generated by deploy/after_install.sh - do not edit by hand."
  echo "RELEASE=$release"
  echo "APP_PORT=4180"
  while IFS=$'\t' read -r name value; do
    [ -n "$name" ] && echo "${name##*/}=$value"
  done <<< "$params"
} > "$ENV_FILE"

for required in OAUTH2_CLIENT_ID OAUTH2_CLIENT_SECRET OAUTH2_COOKIE_SECRET PUBLIC_URL POSTGRES_PASSWORD; do
  grep -q "^$required=." "$ENV_FILE" || { log "ERROR: SSM parameter $SSM_PATH/$required is missing"; exit 1; }
done

log "building images for release $release (this takes a few minutes)"
compose build
log "build complete"
